#!/usr/bin/env bash

export NPM_REGISTRIES="|https://registry-1.com/|token-1"

echo "Set the invalid NPM_REGISTRIES"
echo $NPM_REGISTRIES
echo ""

use_dir=$(pwd)

# Create the env file here because that is the way Heroku does it:
# file location: ENV_DIR/NPM_REGISTRIES
touch NPM_REGISTRIES

# Run the actual compile command with passing three arguments
# First: the BUILD_DIR
# Second: the CACHE_DIR
# Third: the ENV_DIR
./bin/compile "$use_dir" "$use_dir" "$use_dir"
exit_status=$?

# Delete the env file
rm -rf NPM_REGISTRIES

echo ""
echo "#####################################################"
echo ""

if [ $exit_status -ne 1 ]; then
    echo "FAIL: The script did not fail as expected"
    exit 1
else
    echo "SUCCESS: The script failed as expected"
fi