#!/usr/bin/env bash

use_dir=$(pwd)

# Run the actual compile command with passing three arguments
# First: the BUILD_DIR
# Second: the CACHE_DIR
# Third: the ENV_DIR
echo "START COMMAND OUTPUT"
./bin/compile $use_dir $use_dir $use_dir
exit_status=$?
echo "EMD COMMAND OUTPUT"

echo ""
echo "#####################################################"
echo ""

filename=".npmrc"

if [ -f ${filename} ]; then
  echo "Failed! Created the $filename even though no env was provided."
  exit 1
fi

if [ $exit_status -eq 1 ]; then
    echo "FAIL: The script did not fail as expected"
    exit 1
else
    echo "SUCCESS: $filename was not created and the script exited gracefully"
fi
