#!/usr/bin/env bash

export NPM_REGISTRIES="namespace-1|https://registry-1.com/|token-1;namespace-2|http://registry-2.com/|token-2"

echo "Set the NPM_REGISTRIES"
echo $NPM_REGISTRIES
echo ""

use_dir=$(pwd)

# Create the env file here because that is the way Heroku does it:
# file location: ENV_DIR/NPM_REGISTRIES
touch NPM_REGISTRIES
echo $NPM_REGISTRIES > NPM_REGISTRIES

# Run the actual compile command with passing three arguments
# First: the BUILD_DIR
# Second: the CACHE_DIR
# Third: the ENV_DIR
echo "START COMMAND OUTPUT"
(./bin/compile $use_dir $use_dir $use_dir)
echo "EMD COMMAND OUTPUT"

# Delete the env file
rm -rf NPM_REGISTRIES

echo ""
echo "#####################################################"
echo ""

filename=".npmrc"

actual=$(cat "$filename")

expected="@namespace-1:registry=https://registry-1.com/
//registry-1.com/:_authToken=token-1
@namespace-2:registry=http://registry-2.com/
//registry-2.com/:_authToken=token-2"

if [ "$actual" != "$expected" ]
then
    echo "FAIL: $filename is not as expected, got:"
    echo ""
    echo "Actual:"
    cat $filename

    echo ""
    echo "Expected:"
    echo "$expected"
    rm -rf $filename
    exit 1
fi

echo "SUCCESS: $filename is as expected"
echo ""
cat $filename
rm -rf $filename